### ISSUE TITLE
Arrray/tuple as function argument types

### ISSUE THREAD

**Issue by tokland** [puffnfresh/roy#98]
Are these constructions planned to be supported (or did I just use the wrong syntax?):

```
let duplicate_list (x:Number) : [Number] = [x, x]
console.log (duplicate_list 12)

let duplicate_tuple (x:Number) : (Number, Number) = (x, x)
console.log (duplicate_tuple 12)
```

**Comment by puffnfresh** [comment]
Syntax is good, my parser is bad. I'll fix that up.

**Comment by puffnfresh** [comment]
Fixed in c3deb1617e6fc6df9f57fb6464ab5ea6e79f1e23

**Comment by tokland** [comment]
That was fast, thanks! Now the code is working, but I still have a problem with tuples (maybe it's not related and I should open a new issue?):

```
let triplicate_tuple (x:Number) : (Number, Number) = (x, x, x)
console.log (triplicate_tuple 5)
#=> [ 5, 5, 5 ]
```

I guess the type-system should not allow that...
